[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bionemo-scdl"
license.file = "LICENSE"
version = "0.0.1"
readme = "README.md"
description = "SCDL, a Dataset class for Single Cell data."
authors = [
    { name = "John St. John", email = "jstjohn@nvidia.com" },
    { name = "Malcolm Greaves", email = "mgreaves@nvidia.com" },
    { name = "Polina Binder", email = "pbinder@nvidia.com" },
    { name = "Eric Dawson", email = "edawson@nvidia.com" },
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["src"]
include=["bionemo.*"]
namespaces = true
exclude = ["test*."]
