[tool.black]
line-length = 119
target-version = ['py310']
skip-string-normalization = true

[tool.ruff]
line-length = 119

[tool.ruff.lint]
ignore = ["C901", "E741", "E501", "D100", "RUF005", "RUF010", "D205", "D102", "D417", "D101"]
select = [
    "C",    # Pylint conventions
    "E",    # style stuff, whitespaces
    "F",    # important pyflakes lints
    "I",    # import sorting
    "W",    # Pylint warnings
    "D",    # Documentation formatting
    "RUF",  # Some Ruff-specific lints, unused noqas, etc.
]

# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104", "E402", "F401", "F403", "F811",]
"test_*.py" = ["D",]
"scripts/*.py" = ["D",]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["bionemo"]

[tool.ruff.lint.pydocstyle]
convention = "google"
